version: '3.8'

services:
  emqx:
    image: emqx:5.3.0
    container_name: sf-emqx
    ports:
      - "18083:18083" # Dashboard
      - "1883:1883"   # MQTT
      - "8083:8083"   # WebSocket
    environment:
      - "EMQX_DASHBOARD__LISTENERS__HTTP__MAX_HEADER_SIZE=64KB"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
